//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QingYunSoft.VentasWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", ConfigurationName="VentasWS.VentasWS")]
    public interface VentasWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/modificarProductoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/modificarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.VentasWS.modificarProductoResponse modificarProducto(QingYunSoft.VentasWS.modificarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/modificarProductoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/modificarProductoResponse")]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.modificarProductoResponse> modificarProductoAsync(QingYunSoft.VentasWS.modificarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/listarProductosPorNombreRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/listarProductosPorNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.VentasWS.listarProductosPorNombreResponse listarProductosPorNombre(QingYunSoft.VentasWS.listarProductosPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/listarProductosPorNombreRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/listarProductosPorNombreResponse")]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.listarProductosPorNombreResponse> listarProductosPorNombreAsync(QingYunSoft.VentasWS.listarProductosPorNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/listarAlmacenPorNombreRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/listarAlmacenPorNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.VentasWS.listarAlmacenPorNombreResponse listarAlmacenPorNombre(QingYunSoft.VentasWS.listarAlmacenPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/listarAlmacenPorNombreRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/listarAlmacenPorNombreResponse")]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.listarAlmacenPorNombreResponse> listarAlmacenPorNombreAsync(QingYunSoft.VentasWS.listarAlmacenPorNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/eliminarProductoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/eliminarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.VentasWS.eliminarProductoResponse eliminarProducto(QingYunSoft.VentasWS.eliminarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/eliminarProductoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/eliminarProductoResponse")]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.eliminarProductoResponse> eliminarProductoAsync(QingYunSoft.VentasWS.eliminarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/listarProductosRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/listarProductosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.VentasWS.listarProductosResponse listarProductos(QingYunSoft.VentasWS.listarProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/listarProductosRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/listarProductosResponse")]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.listarProductosResponse> listarProductosAsync(QingYunSoft.VentasWS.listarProductosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/insertarAlmacenRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/insertarAlmacenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.VentasWS.insertarAlmacenResponse insertarAlmacen(QingYunSoft.VentasWS.insertarAlmacenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/insertarAlmacenRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/insertarAlmacenResponse")]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.insertarAlmacenResponse> insertarAlmacenAsync(QingYunSoft.VentasWS.insertarAlmacenRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/modificarAlmacenRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/modificarAlmacenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.VentasWS.modificarAlmacenResponse modificarAlmacen(QingYunSoft.VentasWS.modificarAlmacenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/modificarAlmacenRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/modificarAlmacenResponse")]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.modificarAlmacenResponse> modificarAlmacenAsync(QingYunSoft.VentasWS.modificarAlmacenRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/eliminarAlmacenRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/eliminarAlmacenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.VentasWS.eliminarAlmacenResponse eliminarAlmacen(QingYunSoft.VentasWS.eliminarAlmacenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/eliminarAlmacenRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/eliminarAlmacenResponse")]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.eliminarAlmacenResponse> eliminarAlmacenAsync(QingYunSoft.VentasWS.eliminarAlmacenRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/insertarProductoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/insertarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.VentasWS.insertarProductoResponse insertarProducto(QingYunSoft.VentasWS.insertarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/insertarProductoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/insertarProductoResponse")]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.insertarProductoResponse> insertarProductoAsync(QingYunSoft.VentasWS.insertarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/listarAlmacenRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/listarAlmacenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.VentasWS.listarAlmacenResponse listarAlmacen(QingYunSoft.VentasWS.listarAlmacenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/VentasWS/listarAlmacenRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/VentasWS/listarAlmacenResponse")]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.listarAlmacenResponse> listarAlmacenAsync(QingYunSoft.VentasWS.listarAlmacenRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int cantidadField;
        
        private string codigoLoteField;
        
        private double costoField;
        
        private bool devueltoField;
        
        private System.DateTime fechaDeIngresoField;
        
        private bool fechaDeIngresoFieldSpecified;
        
        private int idField;
        
        private int idAlamcenField;
        
        private string nombreField;
        
        private double precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoLote {
            get {
                return this.codigoLoteField;
            }
            set {
                this.codigoLoteField = value;
                this.RaisePropertyChanged("codigoLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool devuelto {
            get {
                return this.devueltoField;
            }
            set {
                this.devueltoField = value;
                this.RaisePropertyChanged("devuelto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaDeIngreso {
            get {
                return this.fechaDeIngresoField;
            }
            set {
                this.fechaDeIngresoField = value;
                this.RaisePropertyChanged("fechaDeIngreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaDeIngresoSpecified {
            get {
                return this.fechaDeIngresoFieldSpecified;
            }
            set {
                this.fechaDeIngresoFieldSpecified = value;
                this.RaisePropertyChanged("fechaDeIngresoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idAlamcen {
            get {
                return this.idAlamcenField;
            }
            set {
                this.idAlamcenField = value;
                this.RaisePropertyChanged("idAlamcen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class almacen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string direccionField;
        
        private int idField;
        
        private string nombreField;
        
        private producto[] productosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("productos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public producto[] productos {
            get {
                return this.productosField;
            }
            set {
                this.productosField = value;
                this.RaisePropertyChanged("productos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarProducto", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.VentasWS.producto producto;
        
        public modificarProductoRequest() {
        }
        
        public modificarProductoRequest(QingYunSoft.VentasWS.producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarProductoResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarProductoResponse() {
        }
        
        public modificarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosPorNombre", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarProductosPorNombreRequest() {
        }
        
        public listarProductosPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosPorNombreResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.VentasWS.producto[] @return;
        
        public listarProductosPorNombreResponse() {
        }
        
        public listarProductosPorNombreResponse(QingYunSoft.VentasWS.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlmacenPorNombre", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAlmacenPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarAlmacenPorNombreRequest() {
        }
        
        public listarAlmacenPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlmacenPorNombreResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAlmacenPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.VentasWS.almacen[] @return;
        
        public listarAlmacenPorNombreResponse() {
        }
        
        public listarAlmacenPorNombreResponse(QingYunSoft.VentasWS.almacen[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProducto", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int producto;
        
        public eliminarProductoRequest() {
        }
        
        public eliminarProductoRequest(int producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProductoResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarProductoResponse() {
        }
        
        public eliminarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductos", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosRequest {
        
        public listarProductosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.VentasWS.producto[] @return;
        
        public listarProductosResponse() {
        }
        
        public listarProductosResponse(QingYunSoft.VentasWS.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAlmacen", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarAlmacenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.VentasWS.almacen almacen;
        
        public insertarAlmacenRequest() {
        }
        
        public insertarAlmacenRequest(QingYunSoft.VentasWS.almacen almacen) {
            this.almacen = almacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAlmacenResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarAlmacenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarAlmacenResponse() {
        }
        
        public insertarAlmacenResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAlmacen", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarAlmacenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.VentasWS.almacen almacen;
        
        public modificarAlmacenRequest() {
        }
        
        public modificarAlmacenRequest(QingYunSoft.VentasWS.almacen almacen) {
            this.almacen = almacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAlmacenResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarAlmacenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarAlmacenResponse() {
        }
        
        public modificarAlmacenResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAlmacen", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarAlmacenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int almacen;
        
        public eliminarAlmacenRequest() {
        }
        
        public eliminarAlmacenRequest(int almacen) {
            this.almacen = almacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAlmacenResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarAlmacenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarAlmacenResponse() {
        }
        
        public eliminarAlmacenResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProducto", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.VentasWS.producto producto;
        
        public insertarProductoRequest() {
        }
        
        public insertarProductoRequest(QingYunSoft.VentasWS.producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProductoResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarProductoResponse() {
        }
        
        public insertarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlmacen", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAlmacenRequest {
        
        public listarAlmacenRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlmacenResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAlmacenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.VentasWS.almacen[] @return;
        
        public listarAlmacenResponse() {
        }
        
        public listarAlmacenResponse(QingYunSoft.VentasWS.almacen[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VentasWSChannel : QingYunSoft.VentasWS.VentasWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentasWSClient : System.ServiceModel.ClientBase<QingYunSoft.VentasWS.VentasWS>, QingYunSoft.VentasWS.VentasWS {
        
        public VentasWSClient() {
        }
        
        public VentasWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VentasWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentasWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentasWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.VentasWS.modificarProductoResponse QingYunSoft.VentasWS.VentasWS.modificarProducto(QingYunSoft.VentasWS.modificarProductoRequest request) {
            return base.Channel.modificarProducto(request);
        }
        
        public int modificarProducto(QingYunSoft.VentasWS.producto producto) {
            QingYunSoft.VentasWS.modificarProductoRequest inValue = new QingYunSoft.VentasWS.modificarProductoRequest();
            inValue.producto = producto;
            QingYunSoft.VentasWS.modificarProductoResponse retVal = ((QingYunSoft.VentasWS.VentasWS)(this)).modificarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.modificarProductoResponse> QingYunSoft.VentasWS.VentasWS.modificarProductoAsync(QingYunSoft.VentasWS.modificarProductoRequest request) {
            return base.Channel.modificarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.VentasWS.modificarProductoResponse> modificarProductoAsync(QingYunSoft.VentasWS.producto producto) {
            QingYunSoft.VentasWS.modificarProductoRequest inValue = new QingYunSoft.VentasWS.modificarProductoRequest();
            inValue.producto = producto;
            return ((QingYunSoft.VentasWS.VentasWS)(this)).modificarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.VentasWS.listarProductosPorNombreResponse QingYunSoft.VentasWS.VentasWS.listarProductosPorNombre(QingYunSoft.VentasWS.listarProductosPorNombreRequest request) {
            return base.Channel.listarProductosPorNombre(request);
        }
        
        public QingYunSoft.VentasWS.producto[] listarProductosPorNombre(string nombre) {
            QingYunSoft.VentasWS.listarProductosPorNombreRequest inValue = new QingYunSoft.VentasWS.listarProductosPorNombreRequest();
            inValue.nombre = nombre;
            QingYunSoft.VentasWS.listarProductosPorNombreResponse retVal = ((QingYunSoft.VentasWS.VentasWS)(this)).listarProductosPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.listarProductosPorNombreResponse> QingYunSoft.VentasWS.VentasWS.listarProductosPorNombreAsync(QingYunSoft.VentasWS.listarProductosPorNombreRequest request) {
            return base.Channel.listarProductosPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.VentasWS.listarProductosPorNombreResponse> listarProductosPorNombreAsync(string nombre) {
            QingYunSoft.VentasWS.listarProductosPorNombreRequest inValue = new QingYunSoft.VentasWS.listarProductosPorNombreRequest();
            inValue.nombre = nombre;
            return ((QingYunSoft.VentasWS.VentasWS)(this)).listarProductosPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.VentasWS.listarAlmacenPorNombreResponse QingYunSoft.VentasWS.VentasWS.listarAlmacenPorNombre(QingYunSoft.VentasWS.listarAlmacenPorNombreRequest request) {
            return base.Channel.listarAlmacenPorNombre(request);
        }
        
        public QingYunSoft.VentasWS.almacen[] listarAlmacenPorNombre(string nombre) {
            QingYunSoft.VentasWS.listarAlmacenPorNombreRequest inValue = new QingYunSoft.VentasWS.listarAlmacenPorNombreRequest();
            inValue.nombre = nombre;
            QingYunSoft.VentasWS.listarAlmacenPorNombreResponse retVal = ((QingYunSoft.VentasWS.VentasWS)(this)).listarAlmacenPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.listarAlmacenPorNombreResponse> QingYunSoft.VentasWS.VentasWS.listarAlmacenPorNombreAsync(QingYunSoft.VentasWS.listarAlmacenPorNombreRequest request) {
            return base.Channel.listarAlmacenPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.VentasWS.listarAlmacenPorNombreResponse> listarAlmacenPorNombreAsync(string nombre) {
            QingYunSoft.VentasWS.listarAlmacenPorNombreRequest inValue = new QingYunSoft.VentasWS.listarAlmacenPorNombreRequest();
            inValue.nombre = nombre;
            return ((QingYunSoft.VentasWS.VentasWS)(this)).listarAlmacenPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.VentasWS.eliminarProductoResponse QingYunSoft.VentasWS.VentasWS.eliminarProducto(QingYunSoft.VentasWS.eliminarProductoRequest request) {
            return base.Channel.eliminarProducto(request);
        }
        
        public int eliminarProducto(int producto) {
            QingYunSoft.VentasWS.eliminarProductoRequest inValue = new QingYunSoft.VentasWS.eliminarProductoRequest();
            inValue.producto = producto;
            QingYunSoft.VentasWS.eliminarProductoResponse retVal = ((QingYunSoft.VentasWS.VentasWS)(this)).eliminarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.eliminarProductoResponse> QingYunSoft.VentasWS.VentasWS.eliminarProductoAsync(QingYunSoft.VentasWS.eliminarProductoRequest request) {
            return base.Channel.eliminarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.VentasWS.eliminarProductoResponse> eliminarProductoAsync(int producto) {
            QingYunSoft.VentasWS.eliminarProductoRequest inValue = new QingYunSoft.VentasWS.eliminarProductoRequest();
            inValue.producto = producto;
            return ((QingYunSoft.VentasWS.VentasWS)(this)).eliminarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.VentasWS.listarProductosResponse QingYunSoft.VentasWS.VentasWS.listarProductos(QingYunSoft.VentasWS.listarProductosRequest request) {
            return base.Channel.listarProductos(request);
        }
        
        public QingYunSoft.VentasWS.producto[] listarProductos() {
            QingYunSoft.VentasWS.listarProductosRequest inValue = new QingYunSoft.VentasWS.listarProductosRequest();
            QingYunSoft.VentasWS.listarProductosResponse retVal = ((QingYunSoft.VentasWS.VentasWS)(this)).listarProductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.listarProductosResponse> QingYunSoft.VentasWS.VentasWS.listarProductosAsync(QingYunSoft.VentasWS.listarProductosRequest request) {
            return base.Channel.listarProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.VentasWS.listarProductosResponse> listarProductosAsync() {
            QingYunSoft.VentasWS.listarProductosRequest inValue = new QingYunSoft.VentasWS.listarProductosRequest();
            return ((QingYunSoft.VentasWS.VentasWS)(this)).listarProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.VentasWS.insertarAlmacenResponse QingYunSoft.VentasWS.VentasWS.insertarAlmacen(QingYunSoft.VentasWS.insertarAlmacenRequest request) {
            return base.Channel.insertarAlmacen(request);
        }
        
        public int insertarAlmacen(QingYunSoft.VentasWS.almacen almacen) {
            QingYunSoft.VentasWS.insertarAlmacenRequest inValue = new QingYunSoft.VentasWS.insertarAlmacenRequest();
            inValue.almacen = almacen;
            QingYunSoft.VentasWS.insertarAlmacenResponse retVal = ((QingYunSoft.VentasWS.VentasWS)(this)).insertarAlmacen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.insertarAlmacenResponse> QingYunSoft.VentasWS.VentasWS.insertarAlmacenAsync(QingYunSoft.VentasWS.insertarAlmacenRequest request) {
            return base.Channel.insertarAlmacenAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.VentasWS.insertarAlmacenResponse> insertarAlmacenAsync(QingYunSoft.VentasWS.almacen almacen) {
            QingYunSoft.VentasWS.insertarAlmacenRequest inValue = new QingYunSoft.VentasWS.insertarAlmacenRequest();
            inValue.almacen = almacen;
            return ((QingYunSoft.VentasWS.VentasWS)(this)).insertarAlmacenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.VentasWS.modificarAlmacenResponse QingYunSoft.VentasWS.VentasWS.modificarAlmacen(QingYunSoft.VentasWS.modificarAlmacenRequest request) {
            return base.Channel.modificarAlmacen(request);
        }
        
        public int modificarAlmacen(QingYunSoft.VentasWS.almacen almacen) {
            QingYunSoft.VentasWS.modificarAlmacenRequest inValue = new QingYunSoft.VentasWS.modificarAlmacenRequest();
            inValue.almacen = almacen;
            QingYunSoft.VentasWS.modificarAlmacenResponse retVal = ((QingYunSoft.VentasWS.VentasWS)(this)).modificarAlmacen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.modificarAlmacenResponse> QingYunSoft.VentasWS.VentasWS.modificarAlmacenAsync(QingYunSoft.VentasWS.modificarAlmacenRequest request) {
            return base.Channel.modificarAlmacenAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.VentasWS.modificarAlmacenResponse> modificarAlmacenAsync(QingYunSoft.VentasWS.almacen almacen) {
            QingYunSoft.VentasWS.modificarAlmacenRequest inValue = new QingYunSoft.VentasWS.modificarAlmacenRequest();
            inValue.almacen = almacen;
            return ((QingYunSoft.VentasWS.VentasWS)(this)).modificarAlmacenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.VentasWS.eliminarAlmacenResponse QingYunSoft.VentasWS.VentasWS.eliminarAlmacen(QingYunSoft.VentasWS.eliminarAlmacenRequest request) {
            return base.Channel.eliminarAlmacen(request);
        }
        
        public int eliminarAlmacen(int almacen) {
            QingYunSoft.VentasWS.eliminarAlmacenRequest inValue = new QingYunSoft.VentasWS.eliminarAlmacenRequest();
            inValue.almacen = almacen;
            QingYunSoft.VentasWS.eliminarAlmacenResponse retVal = ((QingYunSoft.VentasWS.VentasWS)(this)).eliminarAlmacen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.eliminarAlmacenResponse> QingYunSoft.VentasWS.VentasWS.eliminarAlmacenAsync(QingYunSoft.VentasWS.eliminarAlmacenRequest request) {
            return base.Channel.eliminarAlmacenAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.VentasWS.eliminarAlmacenResponse> eliminarAlmacenAsync(int almacen) {
            QingYunSoft.VentasWS.eliminarAlmacenRequest inValue = new QingYunSoft.VentasWS.eliminarAlmacenRequest();
            inValue.almacen = almacen;
            return ((QingYunSoft.VentasWS.VentasWS)(this)).eliminarAlmacenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.VentasWS.insertarProductoResponse QingYunSoft.VentasWS.VentasWS.insertarProducto(QingYunSoft.VentasWS.insertarProductoRequest request) {
            return base.Channel.insertarProducto(request);
        }
        
        public int insertarProducto(QingYunSoft.VentasWS.producto producto) {
            QingYunSoft.VentasWS.insertarProductoRequest inValue = new QingYunSoft.VentasWS.insertarProductoRequest();
            inValue.producto = producto;
            QingYunSoft.VentasWS.insertarProductoResponse retVal = ((QingYunSoft.VentasWS.VentasWS)(this)).insertarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.insertarProductoResponse> QingYunSoft.VentasWS.VentasWS.insertarProductoAsync(QingYunSoft.VentasWS.insertarProductoRequest request) {
            return base.Channel.insertarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.VentasWS.insertarProductoResponse> insertarProductoAsync(QingYunSoft.VentasWS.producto producto) {
            QingYunSoft.VentasWS.insertarProductoRequest inValue = new QingYunSoft.VentasWS.insertarProductoRequest();
            inValue.producto = producto;
            return ((QingYunSoft.VentasWS.VentasWS)(this)).insertarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.VentasWS.listarAlmacenResponse QingYunSoft.VentasWS.VentasWS.listarAlmacen(QingYunSoft.VentasWS.listarAlmacenRequest request) {
            return base.Channel.listarAlmacen(request);
        }
        
        public QingYunSoft.VentasWS.almacen[] listarAlmacen() {
            QingYunSoft.VentasWS.listarAlmacenRequest inValue = new QingYunSoft.VentasWS.listarAlmacenRequest();
            QingYunSoft.VentasWS.listarAlmacenResponse retVal = ((QingYunSoft.VentasWS.VentasWS)(this)).listarAlmacen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.VentasWS.listarAlmacenResponse> QingYunSoft.VentasWS.VentasWS.listarAlmacenAsync(QingYunSoft.VentasWS.listarAlmacenRequest request) {
            return base.Channel.listarAlmacenAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.VentasWS.listarAlmacenResponse> listarAlmacenAsync() {
            QingYunSoft.VentasWS.listarAlmacenRequest inValue = new QingYunSoft.VentasWS.listarAlmacenRequest();
            return ((QingYunSoft.VentasWS.VentasWS)(this)).listarAlmacenAsync(inValue);
        }
    }
}
