//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QingYunSoft.ReportesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", ConfigurationName="ReportesWS.ReporteWS")]
    public interface ReporteWS {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.lp2soft.pucp.edu.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/ReporteWS/generarReporteVendedoresMasVentasRe" +
            "quest", ReplyAction="http://services.lp2soft.pucp.edu.pe/ReporteWS/generarReporteVendedoresMasVentasRe" +
            "sponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasResponse generarReporteVendedoresMasVentas(QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/ReporteWS/generarReporteVendedoresMasVentasRe" +
            "quest", ReplyAction="http://services.lp2soft.pucp.edu.pe/ReporteWS/generarReporteVendedoresMasVentasRe" +
            "sponse")]
        System.Threading.Tasks.Task<QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasResponse> generarReporteVendedoresMasVentasAsync(QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.lp2soft.pucp.edu.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/ReporteWS/generarReporteVentasPeriodoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/ReporteWS/generarReporteVentasPeriodoResponse" +
            "")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.ReportesWS.generarReporteVentasPeriodoResponse generarReporteVentasPeriodo(QingYunSoft.ReportesWS.generarReporteVentasPeriodoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/ReporteWS/generarReporteVentasPeriodoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/ReporteWS/generarReporteVentasPeriodoResponse" +
            "")]
        System.Threading.Tasks.Task<QingYunSoft.ReportesWS.generarReporteVentasPeriodoResponse> generarReporteVentasPeriodoAsync(QingYunSoft.ReportesWS.generarReporteVentasPeriodoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteVendedoresMasVentas", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteVendedoresMasVentasRequest {
        
        public generarReporteVendedoresMasVentasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteVendedoresMasVentasResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteVendedoresMasVentasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public generarReporteVendedoresMasVentasResponse() {
        }
        
        public generarReporteVendedoresMasVentasResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteVentasPeriodo", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteVentasPeriodoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public System.DateTime fecha1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public System.DateTime fecha2;
        
        public generarReporteVentasPeriodoRequest() {
        }
        
        public generarReporteVentasPeriodoRequest(System.DateTime fecha1, System.DateTime fecha2) {
            this.fecha1 = fecha1;
            this.fecha2 = fecha2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteVentasPeriodoResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteVentasPeriodoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public generarReporteVentasPeriodoResponse() {
        }
        
        public generarReporteVentasPeriodoResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReporteWSChannel : QingYunSoft.ReportesWS.ReporteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteWSClient : System.ServiceModel.ClientBase<QingYunSoft.ReportesWS.ReporteWS>, QingYunSoft.ReportesWS.ReporteWS {
        
        public ReporteWSClient() {
        }
        
        public ReporteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasResponse QingYunSoft.ReportesWS.ReporteWS.generarReporteVendedoresMasVentas(QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasRequest request) {
            return base.Channel.generarReporteVendedoresMasVentas(request);
        }
        
        public byte[] generarReporteVendedoresMasVentas() {
            QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasRequest inValue = new QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasRequest();
            QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasResponse retVal = ((QingYunSoft.ReportesWS.ReporteWS)(this)).generarReporteVendedoresMasVentas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasResponse> QingYunSoft.ReportesWS.ReporteWS.generarReporteVendedoresMasVentasAsync(QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasRequest request) {
            return base.Channel.generarReporteVendedoresMasVentasAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasResponse> generarReporteVendedoresMasVentasAsync() {
            QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasRequest inValue = new QingYunSoft.ReportesWS.generarReporteVendedoresMasVentasRequest();
            return ((QingYunSoft.ReportesWS.ReporteWS)(this)).generarReporteVendedoresMasVentasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.ReportesWS.generarReporteVentasPeriodoResponse QingYunSoft.ReportesWS.ReporteWS.generarReporteVentasPeriodo(QingYunSoft.ReportesWS.generarReporteVentasPeriodoRequest request) {
            return base.Channel.generarReporteVentasPeriodo(request);
        }
        
        public byte[] generarReporteVentasPeriodo(System.DateTime fecha1, System.DateTime fecha2) {
            QingYunSoft.ReportesWS.generarReporteVentasPeriodoRequest inValue = new QingYunSoft.ReportesWS.generarReporteVentasPeriodoRequest();
            inValue.fecha1 = fecha1;
            inValue.fecha2 = fecha2;
            QingYunSoft.ReportesWS.generarReporteVentasPeriodoResponse retVal = ((QingYunSoft.ReportesWS.ReporteWS)(this)).generarReporteVentasPeriodo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.ReportesWS.generarReporteVentasPeriodoResponse> QingYunSoft.ReportesWS.ReporteWS.generarReporteVentasPeriodoAsync(QingYunSoft.ReportesWS.generarReporteVentasPeriodoRequest request) {
            return base.Channel.generarReporteVentasPeriodoAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.ReportesWS.generarReporteVentasPeriodoResponse> generarReporteVentasPeriodoAsync(System.DateTime fecha1, System.DateTime fecha2) {
            QingYunSoft.ReportesWS.generarReporteVentasPeriodoRequest inValue = new QingYunSoft.ReportesWS.generarReporteVentasPeriodoRequest();
            inValue.fecha1 = fecha1;
            inValue.fecha2 = fecha2;
            return ((QingYunSoft.ReportesWS.ReporteWS)(this)).generarReporteVentasPeriodoAsync(inValue);
        }
    }
}
