//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QingYunSoft.RRHHWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", ConfigurationName="RRHHWS.RRHHWS")]
    public interface RRHHWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/modificarVendedorRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/modificarVendedorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.RRHHWS.modificarVendedorResponse modificarVendedor(QingYunSoft.RRHHWS.modificarVendedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/modificarVendedorRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/modificarVendedorResponse")]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.modificarVendedorResponse> modificarVendedorAsync(QingYunSoft.RRHHWS.modificarVendedorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/modificarAdministradorRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/modificarAdministradorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.RRHHWS.modificarAdministradorResponse modificarAdministrador(QingYunSoft.RRHHWS.modificarAdministradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/modificarAdministradorRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/modificarAdministradorResponse")]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.modificarAdministradorResponse> modificarAdministradorAsync(QingYunSoft.RRHHWS.modificarAdministradorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarAdministradorRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarAdministradorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.RRHHWS.insertarAdministradorResponse insertarAdministrador(QingYunSoft.RRHHWS.insertarAdministradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarAdministradorRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarAdministradorResponse")]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.insertarAdministradorResponse> insertarAdministradorAsync(QingYunSoft.RRHHWS.insertarAdministradorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarSupervisorRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarSupervisorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.RRHHWS.insertarSupervisorResponse insertarSupervisor(QingYunSoft.RRHHWS.insertarSupervisorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarSupervisorRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarSupervisorResponse")]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.insertarSupervisorResponse> insertarSupervisorAsync(QingYunSoft.RRHHWS.insertarSupervisorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/modificarSupervisorRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/modificarSupervisorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.RRHHWS.modificarSupervisorResponse modificarSupervisor(QingYunSoft.RRHHWS.modificarSupervisorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/modificarSupervisorRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/modificarSupervisorResponse")]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.modificarSupervisorResponse> modificarSupervisorAsync(QingYunSoft.RRHHWS.modificarSupervisorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/verificarCuentaUsuarioRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/verificarCuentaUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.RRHHWS.verificarCuentaUsuarioResponse verificarCuentaUsuario(QingYunSoft.RRHHWS.verificarCuentaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/verificarCuentaUsuarioRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/verificarCuentaUsuarioResponse")]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.verificarCuentaUsuarioResponse> verificarCuentaUsuarioAsync(QingYunSoft.RRHHWS.verificarCuentaUsuarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarUsuarioPorDocumentoNombreRequest" +
            "", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarUsuarioPorDocumentoNombreRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreResponse listarUsuarioPorDocumentoNombre(QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarUsuarioPorDocumentoNombreRequest" +
            "", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarUsuarioPorDocumentoNombreRespons" +
            "e")]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreResponse> listarUsuarioPorDocumentoNombreAsync(QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/eliminarUsuarioRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/eliminarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.RRHHWS.eliminarUsuarioResponse eliminarUsuario(QingYunSoft.RRHHWS.eliminarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/eliminarUsuarioRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/eliminarUsuarioResponse")]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.eliminarUsuarioResponse> eliminarUsuarioAsync(QingYunSoft.RRHHWS.eliminarUsuarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarUsuariosRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarUsuariosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.RRHHWS.listarUsuariosResponse listarUsuarios(QingYunSoft.RRHHWS.listarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarUsuariosRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/listarUsuariosResponse")]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.listarUsuariosResponse> listarUsuariosAsync(QingYunSoft.RRHHWS.listarUsuariosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarVendedorRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarVendedorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QingYunSoft.RRHHWS.insertarVendedorResponse insertarVendedor(QingYunSoft.RRHHWS.insertarVendedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarVendedorRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/RRHHWS/insertarVendedorResponse")]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.insertarVendedorResponse> insertarVendedorAsync(QingYunSoft.RRHHWS.insertarVendedorRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class vendedor : usuario {
        
        private int cantidadVentasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadVentas {
            get {
                return this.cantidadVentasField;
            }
            set {
                this.cantidadVentasField = value;
                this.RaisePropertyChanged("cantidadVentas");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(supervisorDeAlmacen))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vendedor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(administrador))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public abstract partial class usuario : persona {
        
        private System.DateTime fechaIngresoField;
        
        private bool fechaIngresoFieldSpecified;
        
        private byte[] fotoPerfilField;
        
        private int idUsuarioField;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
                this.RaisePropertyChanged("fechaIngreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaIngresoSpecified {
            get {
                return this.fechaIngresoFieldSpecified;
            }
            set {
                this.fechaIngresoFieldSpecified = value;
                this.RaisePropertyChanged("fechaIngresoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] fotoPerfil {
            get {
                return this.fotoPerfilField;
            }
            set {
                this.fotoPerfilField = value;
                this.RaisePropertyChanged("fotoPerfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(supervisorDeAlmacen))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vendedor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(administrador))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string apellidoField;
        
        private string direccionField;
        
        private string emailField;
        
        private System.DateTime fechaDeNacimientoField;
        
        private bool fechaDeNacimientoFieldSpecified;
        
        private int idPersonaField;
        
        private string nombreField;
        
        private string numDeDocumentoField;
        
        private sexo sexoField;
        
        private bool sexoFieldSpecified;
        
        private string telefonoField;
        
        private tipoDeDocumento tipoDeDocumentoField;
        
        private bool tipoDeDocumentoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaDeNacimiento {
            get {
                return this.fechaDeNacimientoField;
            }
            set {
                this.fechaDeNacimientoField = value;
                this.RaisePropertyChanged("fechaDeNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaDeNacimientoSpecified {
            get {
                return this.fechaDeNacimientoFieldSpecified;
            }
            set {
                this.fechaDeNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaDeNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string numDeDocumento {
            get {
                return this.numDeDocumentoField;
            }
            set {
                this.numDeDocumentoField = value;
                this.RaisePropertyChanged("numDeDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public sexo sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sexoSpecified {
            get {
                return this.sexoFieldSpecified;
            }
            set {
                this.sexoFieldSpecified = value;
                this.RaisePropertyChanged("sexoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public tipoDeDocumento tipoDeDocumento {
            get {
                return this.tipoDeDocumentoField;
            }
            set {
                this.tipoDeDocumentoField = value;
                this.RaisePropertyChanged("tipoDeDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDeDocumentoSpecified {
            get {
                return this.tipoDeDocumentoFieldSpecified;
            }
            set {
                this.tipoDeDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("tipoDeDocumentoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public enum sexo {
        
        /// <remarks/>
        Masculino,
        
        /// <remarks/>
        Femenino,
        
        /// <remarks/>
        Otro,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public enum tipoDeDocumento {
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        CE,
        
        /// <remarks/>
        Pasaporte,
        
        /// <remarks/>
        PNAC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class supervisorDeAlmacen : usuario {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class administrador : usuario {
        
        private area areaField;
        
        private bool areaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public area area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaSpecified {
            get {
                return this.areaFieldSpecified;
            }
            set {
                this.areaFieldSpecified = value;
                this.RaisePropertyChanged("areaSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public enum area {
        
        /// <remarks/>
        Cantabilidad,
        
        /// <remarks/>
        RecursosHumanos,
        
        /// <remarks/>
        Ventas,
        
        /// <remarks/>
        Logistica,
        
        /// <remarks/>
        Marketing,
        
        /// <remarks/>
        Sistemas,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarVendedor", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarVendedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.RRHHWS.vendedor vendedor;
        
        public modificarVendedorRequest() {
        }
        
        public modificarVendedorRequest(QingYunSoft.RRHHWS.vendedor vendedor) {
            this.vendedor = vendedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarVendedorResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarVendedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarVendedorResponse() {
        }
        
        public modificarVendedorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAdministrador", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarAdministradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.RRHHWS.administrador administrador;
        
        public modificarAdministradorRequest() {
        }
        
        public modificarAdministradorRequest(QingYunSoft.RRHHWS.administrador administrador) {
            this.administrador = administrador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAdministradorResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarAdministradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarAdministradorResponse() {
        }
        
        public modificarAdministradorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAdministrador", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarAdministradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.RRHHWS.administrador administrador;
        
        public insertarAdministradorRequest() {
        }
        
        public insertarAdministradorRequest(QingYunSoft.RRHHWS.administrador administrador) {
            this.administrador = administrador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAdministradorResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarAdministradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarAdministradorResponse() {
        }
        
        public insertarAdministradorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSupervisor", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSupervisorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.RRHHWS.supervisorDeAlmacen supervisor;
        
        public insertarSupervisorRequest() {
        }
        
        public insertarSupervisorRequest(QingYunSoft.RRHHWS.supervisorDeAlmacen supervisor) {
            this.supervisor = supervisor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSupervisorResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSupervisorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarSupervisorResponse() {
        }
        
        public insertarSupervisorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarSupervisor", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarSupervisorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.RRHHWS.supervisorDeAlmacen supervisor;
        
        public modificarSupervisorRequest() {
        }
        
        public modificarSupervisorRequest(QingYunSoft.RRHHWS.supervisorDeAlmacen supervisor) {
            this.supervisor = supervisor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarSupervisorResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarSupervisorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarSupervisorResponse() {
        }
        
        public modificarSupervisorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarCuentaUsuario", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class verificarCuentaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.RRHHWS.usuario cuentaUsuario;
        
        public verificarCuentaUsuarioRequest() {
        }
        
        public verificarCuentaUsuarioRequest(QingYunSoft.RRHHWS.usuario cuentaUsuario) {
            this.cuentaUsuario = cuentaUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarCuentaUsuarioResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class verificarCuentaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.RRHHWS.usuario @return;
        
        public verificarCuentaUsuarioResponse() {
        }
        
        public verificarCuentaUsuarioResponse(QingYunSoft.RRHHWS.usuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuarioPorDocumentoNombre", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuarioPorDocumentoNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string docNombre;
        
        public listarUsuarioPorDocumentoNombreRequest() {
        }
        
        public listarUsuarioPorDocumentoNombreRequest(string docNombre) {
            this.docNombre = docNombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuarioPorDocumentoNombreResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuarioPorDocumentoNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.RRHHWS.usuario[] @return;
        
        public listarUsuarioPorDocumentoNombreResponse() {
        }
        
        public listarUsuarioPorDocumentoNombreResponse(QingYunSoft.RRHHWS.usuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarUsuario", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.RRHHWS.usuario cuentaUsuario;
        
        public eliminarUsuarioRequest() {
        }
        
        public eliminarUsuarioRequest(QingYunSoft.RRHHWS.usuario cuentaUsuario) {
            this.cuentaUsuario = cuentaUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarUsuarioResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarUsuarioResponse() {
        }
        
        public eliminarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuarios", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuariosRequest {
        
        public listarUsuariosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuariosResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.RRHHWS.usuario[] @return;
        
        public listarUsuariosResponse() {
        }
        
        public listarUsuariosResponse(QingYunSoft.RRHHWS.usuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVendedor", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarVendedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QingYunSoft.RRHHWS.vendedor vendedor;
        
        public insertarVendedorRequest() {
        }
        
        public insertarVendedorRequest(QingYunSoft.RRHHWS.vendedor vendedor) {
            this.vendedor = vendedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVendedorResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarVendedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarVendedorResponse() {
        }
        
        public insertarVendedorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RRHHWSChannel : QingYunSoft.RRHHWS.RRHHWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RRHHWSClient : System.ServiceModel.ClientBase<QingYunSoft.RRHHWS.RRHHWS>, QingYunSoft.RRHHWS.RRHHWS {
        
        public RRHHWSClient() {
        }
        
        public RRHHWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RRHHWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RRHHWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RRHHWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.RRHHWS.modificarVendedorResponse QingYunSoft.RRHHWS.RRHHWS.modificarVendedor(QingYunSoft.RRHHWS.modificarVendedorRequest request) {
            return base.Channel.modificarVendedor(request);
        }
        
        public int modificarVendedor(QingYunSoft.RRHHWS.vendedor vendedor) {
            QingYunSoft.RRHHWS.modificarVendedorRequest inValue = new QingYunSoft.RRHHWS.modificarVendedorRequest();
            inValue.vendedor = vendedor;
            QingYunSoft.RRHHWS.modificarVendedorResponse retVal = ((QingYunSoft.RRHHWS.RRHHWS)(this)).modificarVendedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.modificarVendedorResponse> QingYunSoft.RRHHWS.RRHHWS.modificarVendedorAsync(QingYunSoft.RRHHWS.modificarVendedorRequest request) {
            return base.Channel.modificarVendedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.RRHHWS.modificarVendedorResponse> modificarVendedorAsync(QingYunSoft.RRHHWS.vendedor vendedor) {
            QingYunSoft.RRHHWS.modificarVendedorRequest inValue = new QingYunSoft.RRHHWS.modificarVendedorRequest();
            inValue.vendedor = vendedor;
            return ((QingYunSoft.RRHHWS.RRHHWS)(this)).modificarVendedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.RRHHWS.modificarAdministradorResponse QingYunSoft.RRHHWS.RRHHWS.modificarAdministrador(QingYunSoft.RRHHWS.modificarAdministradorRequest request) {
            return base.Channel.modificarAdministrador(request);
        }
        
        public int modificarAdministrador(QingYunSoft.RRHHWS.administrador administrador) {
            QingYunSoft.RRHHWS.modificarAdministradorRequest inValue = new QingYunSoft.RRHHWS.modificarAdministradorRequest();
            inValue.administrador = administrador;
            QingYunSoft.RRHHWS.modificarAdministradorResponse retVal = ((QingYunSoft.RRHHWS.RRHHWS)(this)).modificarAdministrador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.modificarAdministradorResponse> QingYunSoft.RRHHWS.RRHHWS.modificarAdministradorAsync(QingYunSoft.RRHHWS.modificarAdministradorRequest request) {
            return base.Channel.modificarAdministradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.RRHHWS.modificarAdministradorResponse> modificarAdministradorAsync(QingYunSoft.RRHHWS.administrador administrador) {
            QingYunSoft.RRHHWS.modificarAdministradorRequest inValue = new QingYunSoft.RRHHWS.modificarAdministradorRequest();
            inValue.administrador = administrador;
            return ((QingYunSoft.RRHHWS.RRHHWS)(this)).modificarAdministradorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.RRHHWS.insertarAdministradorResponse QingYunSoft.RRHHWS.RRHHWS.insertarAdministrador(QingYunSoft.RRHHWS.insertarAdministradorRequest request) {
            return base.Channel.insertarAdministrador(request);
        }
        
        public int insertarAdministrador(QingYunSoft.RRHHWS.administrador administrador) {
            QingYunSoft.RRHHWS.insertarAdministradorRequest inValue = new QingYunSoft.RRHHWS.insertarAdministradorRequest();
            inValue.administrador = administrador;
            QingYunSoft.RRHHWS.insertarAdministradorResponse retVal = ((QingYunSoft.RRHHWS.RRHHWS)(this)).insertarAdministrador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.insertarAdministradorResponse> QingYunSoft.RRHHWS.RRHHWS.insertarAdministradorAsync(QingYunSoft.RRHHWS.insertarAdministradorRequest request) {
            return base.Channel.insertarAdministradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.RRHHWS.insertarAdministradorResponse> insertarAdministradorAsync(QingYunSoft.RRHHWS.administrador administrador) {
            QingYunSoft.RRHHWS.insertarAdministradorRequest inValue = new QingYunSoft.RRHHWS.insertarAdministradorRequest();
            inValue.administrador = administrador;
            return ((QingYunSoft.RRHHWS.RRHHWS)(this)).insertarAdministradorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.RRHHWS.insertarSupervisorResponse QingYunSoft.RRHHWS.RRHHWS.insertarSupervisor(QingYunSoft.RRHHWS.insertarSupervisorRequest request) {
            return base.Channel.insertarSupervisor(request);
        }
        
        public int insertarSupervisor(QingYunSoft.RRHHWS.supervisorDeAlmacen supervisor) {
            QingYunSoft.RRHHWS.insertarSupervisorRequest inValue = new QingYunSoft.RRHHWS.insertarSupervisorRequest();
            inValue.supervisor = supervisor;
            QingYunSoft.RRHHWS.insertarSupervisorResponse retVal = ((QingYunSoft.RRHHWS.RRHHWS)(this)).insertarSupervisor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.insertarSupervisorResponse> QingYunSoft.RRHHWS.RRHHWS.insertarSupervisorAsync(QingYunSoft.RRHHWS.insertarSupervisorRequest request) {
            return base.Channel.insertarSupervisorAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.RRHHWS.insertarSupervisorResponse> insertarSupervisorAsync(QingYunSoft.RRHHWS.supervisorDeAlmacen supervisor) {
            QingYunSoft.RRHHWS.insertarSupervisorRequest inValue = new QingYunSoft.RRHHWS.insertarSupervisorRequest();
            inValue.supervisor = supervisor;
            return ((QingYunSoft.RRHHWS.RRHHWS)(this)).insertarSupervisorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.RRHHWS.modificarSupervisorResponse QingYunSoft.RRHHWS.RRHHWS.modificarSupervisor(QingYunSoft.RRHHWS.modificarSupervisorRequest request) {
            return base.Channel.modificarSupervisor(request);
        }
        
        public int modificarSupervisor(QingYunSoft.RRHHWS.supervisorDeAlmacen supervisor) {
            QingYunSoft.RRHHWS.modificarSupervisorRequest inValue = new QingYunSoft.RRHHWS.modificarSupervisorRequest();
            inValue.supervisor = supervisor;
            QingYunSoft.RRHHWS.modificarSupervisorResponse retVal = ((QingYunSoft.RRHHWS.RRHHWS)(this)).modificarSupervisor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.modificarSupervisorResponse> QingYunSoft.RRHHWS.RRHHWS.modificarSupervisorAsync(QingYunSoft.RRHHWS.modificarSupervisorRequest request) {
            return base.Channel.modificarSupervisorAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.RRHHWS.modificarSupervisorResponse> modificarSupervisorAsync(QingYunSoft.RRHHWS.supervisorDeAlmacen supervisor) {
            QingYunSoft.RRHHWS.modificarSupervisorRequest inValue = new QingYunSoft.RRHHWS.modificarSupervisorRequest();
            inValue.supervisor = supervisor;
            return ((QingYunSoft.RRHHWS.RRHHWS)(this)).modificarSupervisorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.RRHHWS.verificarCuentaUsuarioResponse QingYunSoft.RRHHWS.RRHHWS.verificarCuentaUsuario(QingYunSoft.RRHHWS.verificarCuentaUsuarioRequest request) {
            return base.Channel.verificarCuentaUsuario(request);
        }
        
        public QingYunSoft.RRHHWS.usuario verificarCuentaUsuario(QingYunSoft.RRHHWS.usuario cuentaUsuario) {
            QingYunSoft.RRHHWS.verificarCuentaUsuarioRequest inValue = new QingYunSoft.RRHHWS.verificarCuentaUsuarioRequest();
            inValue.cuentaUsuario = cuentaUsuario;
            QingYunSoft.RRHHWS.verificarCuentaUsuarioResponse retVal = ((QingYunSoft.RRHHWS.RRHHWS)(this)).verificarCuentaUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.verificarCuentaUsuarioResponse> QingYunSoft.RRHHWS.RRHHWS.verificarCuentaUsuarioAsync(QingYunSoft.RRHHWS.verificarCuentaUsuarioRequest request) {
            return base.Channel.verificarCuentaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.RRHHWS.verificarCuentaUsuarioResponse> verificarCuentaUsuarioAsync(QingYunSoft.RRHHWS.usuario cuentaUsuario) {
            QingYunSoft.RRHHWS.verificarCuentaUsuarioRequest inValue = new QingYunSoft.RRHHWS.verificarCuentaUsuarioRequest();
            inValue.cuentaUsuario = cuentaUsuario;
            return ((QingYunSoft.RRHHWS.RRHHWS)(this)).verificarCuentaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreResponse QingYunSoft.RRHHWS.RRHHWS.listarUsuarioPorDocumentoNombre(QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreRequest request) {
            return base.Channel.listarUsuarioPorDocumentoNombre(request);
        }
        
        public QingYunSoft.RRHHWS.usuario[] listarUsuarioPorDocumentoNombre(string docNombre) {
            QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreRequest inValue = new QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreRequest();
            inValue.docNombre = docNombre;
            QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreResponse retVal = ((QingYunSoft.RRHHWS.RRHHWS)(this)).listarUsuarioPorDocumentoNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreResponse> QingYunSoft.RRHHWS.RRHHWS.listarUsuarioPorDocumentoNombreAsync(QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreRequest request) {
            return base.Channel.listarUsuarioPorDocumentoNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreResponse> listarUsuarioPorDocumentoNombreAsync(string docNombre) {
            QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreRequest inValue = new QingYunSoft.RRHHWS.listarUsuarioPorDocumentoNombreRequest();
            inValue.docNombre = docNombre;
            return ((QingYunSoft.RRHHWS.RRHHWS)(this)).listarUsuarioPorDocumentoNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.RRHHWS.eliminarUsuarioResponse QingYunSoft.RRHHWS.RRHHWS.eliminarUsuario(QingYunSoft.RRHHWS.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuario(request);
        }
        
        public int eliminarUsuario(QingYunSoft.RRHHWS.usuario cuentaUsuario) {
            QingYunSoft.RRHHWS.eliminarUsuarioRequest inValue = new QingYunSoft.RRHHWS.eliminarUsuarioRequest();
            inValue.cuentaUsuario = cuentaUsuario;
            QingYunSoft.RRHHWS.eliminarUsuarioResponse retVal = ((QingYunSoft.RRHHWS.RRHHWS)(this)).eliminarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.eliminarUsuarioResponse> QingYunSoft.RRHHWS.RRHHWS.eliminarUsuarioAsync(QingYunSoft.RRHHWS.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.RRHHWS.eliminarUsuarioResponse> eliminarUsuarioAsync(QingYunSoft.RRHHWS.usuario cuentaUsuario) {
            QingYunSoft.RRHHWS.eliminarUsuarioRequest inValue = new QingYunSoft.RRHHWS.eliminarUsuarioRequest();
            inValue.cuentaUsuario = cuentaUsuario;
            return ((QingYunSoft.RRHHWS.RRHHWS)(this)).eliminarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.RRHHWS.listarUsuariosResponse QingYunSoft.RRHHWS.RRHHWS.listarUsuarios(QingYunSoft.RRHHWS.listarUsuariosRequest request) {
            return base.Channel.listarUsuarios(request);
        }
        
        public QingYunSoft.RRHHWS.usuario[] listarUsuarios() {
            QingYunSoft.RRHHWS.listarUsuariosRequest inValue = new QingYunSoft.RRHHWS.listarUsuariosRequest();
            QingYunSoft.RRHHWS.listarUsuariosResponse retVal = ((QingYunSoft.RRHHWS.RRHHWS)(this)).listarUsuarios(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.listarUsuariosResponse> QingYunSoft.RRHHWS.RRHHWS.listarUsuariosAsync(QingYunSoft.RRHHWS.listarUsuariosRequest request) {
            return base.Channel.listarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.RRHHWS.listarUsuariosResponse> listarUsuariosAsync() {
            QingYunSoft.RRHHWS.listarUsuariosRequest inValue = new QingYunSoft.RRHHWS.listarUsuariosRequest();
            return ((QingYunSoft.RRHHWS.RRHHWS)(this)).listarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QingYunSoft.RRHHWS.insertarVendedorResponse QingYunSoft.RRHHWS.RRHHWS.insertarVendedor(QingYunSoft.RRHHWS.insertarVendedorRequest request) {
            return base.Channel.insertarVendedor(request);
        }
        
        public int insertarVendedor(QingYunSoft.RRHHWS.vendedor vendedor) {
            QingYunSoft.RRHHWS.insertarVendedorRequest inValue = new QingYunSoft.RRHHWS.insertarVendedorRequest();
            inValue.vendedor = vendedor;
            QingYunSoft.RRHHWS.insertarVendedorResponse retVal = ((QingYunSoft.RRHHWS.RRHHWS)(this)).insertarVendedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QingYunSoft.RRHHWS.insertarVendedorResponse> QingYunSoft.RRHHWS.RRHHWS.insertarVendedorAsync(QingYunSoft.RRHHWS.insertarVendedorRequest request) {
            return base.Channel.insertarVendedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<QingYunSoft.RRHHWS.insertarVendedorResponse> insertarVendedorAsync(QingYunSoft.RRHHWS.vendedor vendedor) {
            QingYunSoft.RRHHWS.insertarVendedorRequest inValue = new QingYunSoft.RRHHWS.insertarVendedorRequest();
            inValue.vendedor = vendedor;
            return ((QingYunSoft.RRHHWS.RRHHWS)(this)).insertarVendedorAsync(inValue);
        }
    }
}
